version: '3.9'
services:
  security:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    volumes:
      - /home/admin/docker/data:/logs
    restart: unless-stopped
